name: Deploy Proxy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify configuration file existence
      run: |
        if [ ! -f $(pwd)/nginx.conf ]; then
          echo "nginx.conf not found!"
          exit 1
        fi

    - name: Set up Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx
        sudo cp $(pwd)/nginx.conf /etc/nginx/nginx.conf
        sudo nginx -t  # Verify Nginx configuration syntax
        sudo systemctl restart nginx || sudo systemctl status nginx.service || sudo journalctl -xeu nginx.service

    - name: Get Nginx error log
      run: |
        echo "Nginx Error Log:"
        sudo tail -n 50 /var/log/nginx/error.log

    - name: Get Nginx access log
      run: |
        echo "Nginx Access Log:"
        sudo tail -n 50 /var/log/nginx/access.log

    - name: Make server request and log response
      run: |
        curl -i "http://localhost/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E(354468,354472)&SUBSET=N(6650556,6650560)&format=text/plain" || { echo "Failed to make request"; exit 1; }
        echo "Request completed, check logs for response."

    - name: Check logs after request
      run: |
        echo "=== Nginx Access Log ==="
        sudo tail -n 100 /var/log/nginx/access.log
        echo "=== Nginx Error Log ==="
        sudo tail -n 100 /var/log/nginx/error.log
