name: Deploy Proxy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify configuration file existence
      run: |
        if [ ! -f $(pwd)/nginx.conf ]; then
          echo "nginx.conf not found!"
          exit 1
        fi
        if [ ! -f $(pwd)/index.html ]; then
          echo "index.html not found!"
          exit 1
        fi

    - name: Set up Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx
        sudo cp $(pwd)/nginx.conf /etc/nginx/nginx.conf
        sudo mkdir -p /var/www/html
        sudo cp $(pwd)/index.html /var/www/html/index.html
        sudo nginx -t  # Verify Nginx configuration syntax
        sudo systemctl restart nginx || sudo systemctl status nginx.service || sudo journalctl -xeu nginx.service

    - name: Get Nginx error log
      run: |
        echo "Nginx Error Log:"
        sudo tail -n 100 /var/log/nginx/error.log

    - name: Get Nginx access log
      run: |
        echo "Nginx Access Log:"
        sudo tail -n 100 /var/log/nginx/access.log

    - name: Verify server is running and log output
      run: |
        curl -I http://localhost || { echo "Failed to connect to server"; exit 1; }
        echo "Server verification completed"
        echo "=== Server Log Output ==="
        cat /var/log/nginx/error.log || echo "No server log found"
        echo "=== End of Server Log Output ==="

    - name: Keep server running and verify periodically
      run: |
        (while true; do
          echo "Verifying server status..."
          curl -sSf "http://localhost/proxy/?api-key=7cd2ddae-9f2e-481c-99d0-404e7bc7a0b2&service=WCS&version=2.0.1&request=GetCoverage&CoverageID=korkeusmalli_2m&SUBSET=E%28354468,354472%29&SUBSET=N%286650556,6650560%29&format=text/plain" -H "Content-Type: application/json" && echo "Status OK" || { echo "Server is down"; break; }
          sleep 10
        done) &
        wait
      continue-on-error: true
