name: Deploy Proxy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify configuration files existence
      run: |
        if [ ! -f $(pwd)/nginx.conf ]; then
          echo "nginx.conf not found!"
          exit 1
        fi
        if [ ! -f $(pwd)/index.html ]; then
          echo "index.html not found!"
          exit 1
        fi

    - name: Set up Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx
        sudo cp $(pwd)/nginx.conf /etc/nginx/nginx.conf
        sudo mkdir -p /var/www/html
        sudo cp $(pwd)/index.html /var/www/html/index.html
        sudo nginx -t  # Verify Nginx configuration syntax
        sudo systemctl restart nginx || sudo systemctl status nginx.service || sudo journalctl -xeu nginx.service

    - name: Get Nginx error log
      run: |
        echo "Nginx Error Log:"
        sudo tail -n 100 /var/log/nginx/error.log

    - name: Get Nginx access log
      run: |
        echo "Nginx Access Log:"
